class TextConstants {
  TextConstants._();

  static const String add = 'Thêm';
  static const String setting = 'Cài đặt';
  static const String expense = 'Chi tiêu';
  static const String income = 'Thu nhập';
  static const String transfer = 'Chuyển khoản';
  static const String home = 'Trang chủ';
  static const String chart = 'Biểu đồ';
  static const String report = 'Báo cáo';
  static const String profile = 'Tôi';
  static const String other = 'Khác';
  static const String select = 'Lựa chọn';
  static const String confirm = 'Đồng ý';
  static const String error = 'Lỗi';
  static const String cancel = 'Huỷ';
  static const String gotIt = 'Đã hiểu';
  static const String note = 'Ghi chú: ';
  static const String amountDefault = '0';
  static const String analysis = 'Phân tích';
  static const String account = 'Tài khoản';
  static const String month = 'Tháng';
  static const String year = 'Năm';
  static const String balance = 'Số dư';

  static const String invalidTransaction = 'Loại giao dịch không hợp lệ';
  static const String categoryNotFound = 'Không tìm thấy danh mục';
  static const String networkError = 'Lỗi kết nối mạng';
  static const String unknownError = 'Lỗi không xác định';
  static const String cancelRequestError = 'Lỗi yêu cầu bị hủy';
  static const String badCertificateError = 'Lỗi chứng chỉ không hợp lệ';

  static const String transactionAddedSuccess = 'Giao dịch đã được thêm thành công';
  static const String categorySelectedSuccess = 'Danh mục đã được chọn';
  static const String requiredField = 'Trường này là bắt buộc';
  static const String invalidAmount = 'Số tiền không hợp lệ';
  static const String invalidDate = 'Ngày không hợp lệ';
  static const String emptyTransaction = 'Chưa có giao dịch nào';
  static const String addTransactionAdvice = 'Hãy thêm giao dịch đầu tiên của bạn';

  static const String changeToVipPackage = 'Chuyển sang gói Premium';
  static const String unlockFeatureAndRemoveAds = 'Mở khoá mọi thứ và loại bỏ quảng cáo';
  static const String moreTopicAndCustomise = 'Nhiều chủ đề đẹp hơn và có thể tuỳ chỉnh';
  static const String makeLifeBeautiful = 'Làm cho cuôc sống bạn tốt hơn';
  static const String feeForYear = '199.000 đ / hàng năm Huỷ bất cứ lúc nào';
  static const String register = 'Đăng ký';
  static const String termPolicy = 'Bằng cách đăng nhập bạn đồng ý với chính sách và quyền riêng tư';
  static const String term = 'Điều khoản sử dung';
  static const String policy = 'Chính sách bảo mật';
  static const String all = 'Tất cả';
  static const String search = 'Tìm kiếm';

  static const String shopping = 'Mua sắm';
  static const String food = 'Đồ ăn';
  static const String telephone = 'Điện thoại';
  static const String entertainment = 'Giải trí';
  static const String education = 'Giáo dục';
  static const String beauty = 'Sắc đẹp';
  static const String sport = 'Thể thao';
  static const String social = 'Xã hội';
  static const String transport = 'Vận tải';
  static const String clothes = 'Quần áo';
  static const String car = 'Xe hơi';
  static const String alcohol = 'Rượu';
  static const String cigarettes = 'Thuốc lá';
  static const String electronic = 'Thiết bị điện tử';
  static const String travel = 'Du lịch';
  static const String health = 'Sức khỏe';
  static const String pet = 'Thú cưng';
  static const String repair = 'Sửa chữa';
  static const String house = 'Nhà ở';
  static const String gift = 'Quà tặng';
  static const String donate = 'Quyên góp';
  static const String lottery = 'Vé số';
  static const String snack = 'Đồ ăn nhẹ';
  static const String children = 'Trẻ em';
  static const String vegetable = 'Rau quả';
  static const String fruit = 'Hoa quả';
  static const String salary = 'Lương';
  static const String bonus = 'Thưởng';
  static const String interest = 'Tiền lãi';
  static const String incomeAndExpenditureBook = 'Sổ thu chi';
}
